config/routes.rb
Rails.application.routes.draw do
  resources :beans

end

app/models/bean.rb
class Bean < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beans_controller.rb
class BeansController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beans_helper.rb
module BeansHelper
end

app/views/beans/_form.html.erb
<%= form_for(@bean) do |f| %>
  <% if @bean.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bean.errors.count, "error") %> prohibited this bean from being saved:</h2>

      <ul>
      <% @bean.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :in_stock %><br>
    <%= f.check_box :in_stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beans/edit.html.erb
<h1>Editing Bean</h1>

<%= render 'form' %>

<%= link_to 'Show', @bean %> |
<%= link_to 'Back', beans_path %>

app/views/beans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Origin</th>
      <th>Price</th>
      <th>In stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beans.each do |bean| %>
      <tr>
        <td><%= bean.name %></td>
        <td><%= bean.origin %></td>
        <td><%= bean.price %></td>
        <td><%= bean.in_stock %></td>
        <td><%= link_to 'Show', bean %></td>
        <td><%= link_to 'Edit', edit_bean_path(bean) %></td>
        <td><%= link_to 'Destroy', bean, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bean', new_bean_path %>

app/views/beans/new.html.erb
<h1>New Bean</h1>

<%= render 'form' %>

<%= link_to 'Back', beans_path %>

app/views/beans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bean.name %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @bean.origin %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bean.price %>
</p>

<p>
  <strong>In stock:</strong>
  <%= @bean.in_stock %>
</p>

<%= link_to 'Edit', edit_bean_path(@bean) %> |
<%= link_to 'Back', beans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoffeeShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>